import { env } from '@/config/env';
import { buildMessage, SmsProvider, SmsProviderError } from '@/modules/otp/providers/types';

/**
 * Twilio — international fallback (anyone not routed to 2Factor or Sparrow).
 * Twilio has no OTP-generation endpoint of its own, so it sends `localCode`
 * (generated by `otp.service.ts`) and echoes it back unchanged.
 */
export const twilioProvider: SmsProvider = {
  async send(phone: string, localCode: string, expiryMinutes: number): Promise<string> {
    if (!env.TWILIO_ACCOUNT_SID || !env.TWILIO_AUTH_TOKEN || !env.TWILIO_FROM_NUMBER) {
      throw new SmsProviderError('twilio', 'Twilio credentials are not configured');
    }

    const url = `https://api.twilio.com/2010-04-01/Accounts/${env.TWILIO_ACCOUNT_SID}/Messages.json`;
    const body = new URLSearchParams({
      To: phone,
      From: env.TWILIO_FROM_NUMBER,
      Body: buildMessage(localCode, expiryMinutes),
    });
    const auth = Buffer.from(`${env.TWILIO_ACCOUNT_SID}:${env.TWILIO_AUTH_TOKEN}`).toString('base64');

    const res = await fetch(url, {
      method: 'POST',
      headers: {
        Authorization: `Basic ${auth}`,
        'Content-Type': 'application/x-www-form-urlencoded',
      },
      body,
    });

    if (!res.ok) {
      const errBody = (await res.json().catch(() => null)) as { message?: string } | null;
      throw new SmsProviderError(
        'twilio',
        `SMS send failed: ${errBody?.message ?? res.statusText ?? 'unknown error'}`,
      );
    }

    return localCode;
  },
};
